# Generated by Django 4.2.6 on 2023-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField()),
                ('project_url_on_catalog', models.TextField()),
                ('project_url_external', models.TextField()),
                ('project_description', models.TextField()),
                ('keywords', models.TextField()),
                ('fields_of_science', models.TextField()),
                ('project_status', models.TextField()),
                ('agency_sponsor', models.TextField()),
                ('agency_sponsor_other', models.TextField()),
                ('geographic_scope', models.TextField()),
                ('participant_age', models.TextField()),
                ('project_goals', models.TextField()),
                ('participation_tasks', models.TextField()),
                ('scistarter', models.TextField()),
                ('email', models.TextField()),
                ('start_date', models.TextField()),
            ],
        ),
    ]
