# Generated by Django 4.2.6 on 2023-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, null=True, verbose_name=1024),
        ),
    ]
