# Generated by Django 4.2.6 on 2023-10-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_goals',
            field=models.CharField(default='Default goals', max_length=255),
        ),
    ]
