# Generated by Django 4.2.6 on 2023-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_project_project_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_goals',
            field=models.CharField(blank=True, null=True),
        ),
    ]
