# Generated by Django 4.2.6 on 2023-10-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agency_sponsor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='agency_sponsor_other',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='fields_of_science',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='geographic_scope',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='participant_age',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='participation_tasks',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_goals',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url_external',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url_on_catalog',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='scistarter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(max_length=255),
        ),
    ]
