# Generated by Django 4.2.6 on 2023-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='geographic_scope',
            field=models.CharField(max_length=255),
        ),
    ]
